version: '3.5'
services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    container_name: starbudget
    command: uvicorn app:app --host 0.0.0.0 --port 8000
