version: '3.5'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  database:
    image: postgres:14
    restart: always
    env_file:
      - .env
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    networks:
      - db
    container_name: db
  starbudget:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - db
    restart: always
    container_name: starbudget
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --ssl-keyfile /etc/nginx/ssl/live/starbudget.rmblau.com/privkey.pem --ssl-certfile /etc/nginx/ssl/live/starbudget.rmblau.com/fullchain.pem

networks:
  db: null
