version: '3.5'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - db
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - db
    command: certonly --webroot --webroot-path /var/www/certbot/ -d starbudget.rmblau.com
  database:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    networks:
      - db
    container_name: db
  starbudget:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - db
    restart: always
    container_name: starbudget
    depends_on: certbot
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --proxy-headers --ssl-keyfile /etc/nginx/ssl/live/starbudget.rmblau.com/privkey.pem --ssl-certfile /etc/nginx/ssl/live/starbudget.rmblau.com/fullchain.pem

networks:
  db: null
